name: Publish Packages
on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Upload JAR to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
